apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopswebapp
  labels:
    app: devopswebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopswebapp
  template:
    metadata:
      labels:
        app: devopswebapp
    spec:
      containers:
        - name: devopswebapp
          image: nanmycontreg.azurecr.io/devopswebapp
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: devopswebapp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devopswebapp
  name: devopswebapp
spec:
  type: NodePort
  ports:
  - name: "devopswebapp-service"
    port: 5001
    targetPort: 80
    nodePort: 31001
  selector:
    app: devopswebapp
